package com.safetynet.alerts.model;

import java.util.Objects;
/**
 * FireStation class used to contain fire station data
 * 
 * @author Fatima
 *
 */
public class FireStation {
	/**
	 * address covered by fire station
	 */
	private String address;

	/**
	 * fire station number
	 */
	private int station;
	/**
	 * all fields constructor
	 * 
	 * @param address
	 *            covered address
	 * @param station
	 *            fire station number
	 */
	public FireStation(String address, int station) {

		this.address = address;
		this.station = station;
	}
	/**
	 * empty class constructor
	 */
	public FireStation() {

	}

	/**
	 * Getter of Firestation address
	 * 
	 * @return address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Setter of FireStation address
	 * 
	 * @param address
	 *            to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Getter of fire station number
	 * 
	 * @return station number
	 */
	public int getStation() {
		return station;
	}

	/**
	 * Setter of fire station number
	 * 
	 * @param station
	 *            number to set
	 */
	public void setStation(int station) {
		this.station = station;
	}
	/**
	 * returns an integer value, generated by a hashing algorithm.
	 */
	@Override
	public int hashCode() {
		return Objects.hash(address, station);
	}
	/**
	 * checks if an object is equal to this Firestation
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		FireStation other = (FireStation) obj;
		return Objects.equals(address, other.address)
				&& station == other.station;
	}
	/**
	 * Serialization toString method.
	 */
	@Override
	public String toString() {
		return "FireStation [address=" + address + ", station=" + station + "]";
	}

}
