package com.safetynet.alerts.model;

import java.util.List;
import java.util.Objects;
/**
 * MedicalRecord class, is used to contain the medical data of persons
 * 
 * @author Fatima
 *
 */
public class MedicalRecord {

	/**
	 * person's first name
	 */
	private String firstName;

	/**
	 * person's last name
	 */
	private String lastName;

	/*
	 * person's birthdate
	 */
	private String birthdate;

	/**
	 * person's medications
	 */
	private List<String> medications;

	/**
	 * person's allergies
	 */
	private List<String> allergies;

	/**
	 * empty class constructor
	 */

	public MedicalRecord() {
	}

	/**
	 * all fields class constructor
	 * 
	 * @param firstName
	 * @param lastName
	 * @param birthdate
	 * @param medications
	 * @param allergies
	 */
	public MedicalRecord(String firstName, String lastName, String birthdate,
			List<String> medications, List<String> allergies) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthdate = birthdate;
		this.medications = medications;
		this.allergies = allergies;
	}

	/**
	 * Getter of person's first name
	 * 
	 * @return person's first name
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Setter of person's first name
	 * 
	 * @param firstName
	 *            to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * Getter of person's last name
	 * 
	 * @return person's last name
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Setter of person's last name
	 * 
	 * @param lastName
	 *            to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * Getter of person's birth date
	 * 
	 * @return person's birth date
	 */
	public String getBirthdate() {
		return birthdate;
	}

	/**
	 * Setter of person's birth date
	 * 
	 * @param birthdate
	 *            to set
	 */
	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * Getter of person's medications
	 * 
	 * @return person's medications
	 */
	public List<String> getMedications() {
		return medications;
	}

	/**
	 * Setter of person's medications
	 * 
	 * @param medications
	 *            to set
	 */
	public void setMedications(List<String> medications) {
		this.medications = medications;
	}

	/**
	 * Getter of person's allergies
	 * 
	 * @return person's allergies
	 */
	public List<String> getAllergies() {
		return allergies;
	}

	/**
	 * Setter of person's allergies
	 * 
	 * @param allergies
	 *            to set
	 */
	public void setAllergies(List<String> allergies) {
		this.allergies = allergies;
	}

	/**
	 * Serialization toString method.
	 */
	@Override
	public String toString() {
		return "MedicalRecord [firstName=" + firstName + ", lastName="
				+ lastName + ", birthdate=" + birthdate + ", medications="
				+ medications + ", allergies=" + allergies + "]";
	}

	/**
	 * returns an integer value, generated by a hashing algorithm.
	 */
	@Override
	public int hashCode() {
		return Objects.hash(allergies, birthdate, firstName, lastName,
				medications);
	}

	/**
	 * checks if an object is equal to this MedicalRecord
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MedicalRecord other = (MedicalRecord) obj;
		return Objects.equals(allergies, other.allergies)
				&& Objects.equals(birthdate, other.birthdate)
				&& Objects.equals(firstName, other.firstName)
				&& Objects.equals(lastName, other.lastName)
				&& Objects.equals(medications, other.medications);
	}

}
